data:
  buffer_size: 50000
  data_dir: data/traffic/rl_data/rl_data.parquet
  val_periods: [25, 26, 27]

environment:
  environment: OfflineBiddingEnv
  environment_params: {}

general:
  project_path: /work/daniel.gratti/auto-bidding
  project_name: bidding_train_env
  experiment_name: td3bc
  device: cuda
  seed: 42
  
model:
  actor: NormalStochasticMLP
  actor_params:
    activation: relu
    input_dim: 16
    hidden_dims: [256, 256]
    output_dim: 1

  budget: 750.0
  category: 0
  cpa: 8.0
  critic: QEmbedMLP
  critic_params:
    observation_shape: [16]
    action_shape: []
    embedding_dim: 64
    hidden_dims: [256, 256]
    activation: relu

  num_critics: 2
  strategy: SimpleBiddingStrategy

train:
  actor_optimizer: Adam
  actor_optimizer_params:
    lr: 0.001
  actor_update_freq: 2
  alpha: 0.2
  batch_size: 128
  critic_optimizer: Adam
  critic_optimizer_params:
    lr: 0.001
  gamma: 0.99
  noise_clip: 0.5
  noise_std: 0.2
  num_epochs: 10
  steps_per_epoch: 1000
  tau: 0.005

logging:
  log_dir: logs/td3bc
  checkpoint_interval: 1000
  use_wandb: true
  verbose: false