general:
  seed: 42
  device: "cuda:2"
  project_name: "bidding_train_env"

data:
  data_dir: "data/traffic/rl_data/rl_data.parquet"
  buffer_size: 50000
  train_periods: [7, 8, 9, 10]
  val_periods: [11, 12, 13]

environment:
  environment: "OfflineBiddingEnv"
  observation_shape: [16]
  action_shape: []

model:
  actor: "Transformer"
  actor_params:
    state_dim: 16
    act_dim: 1
    K: 20
    max_ep_len: 48
    hidden_size: 64
    d_model: 64
    transformer_num_layers: 3
    nhead: 1
    dim_feedforward: 256
    activation: "relu"
    dropout: 0.1
  strategy: "SimpleBiddingStrategy"

train:
  batch_size: 64
  num_epochs: 1
  steps_per_epoch: 100
  actor_optimizer: "AdamW"
  actor_optimizer_params:
    lr: 1e-4
  trajectory_window: 20

logging:
  log_dir: "logs/dt"
  checkpoint_interval: 1000
  use_wandb: false
