general:
  seed: 42
  device: "cpu"
  project_name: "bidding_train_env"
  experiment_name: "partial-punisher-1"

data:
  data_dir: "data/traffic/new_rl_data/partial_punisher_data_new.parquet"
  buffer_size: 50000
  train_periods: [7, 8, 9, 10, 11, 12]
  val_periods: [13]

environment:
  environment: "OfflineBiddingEnv"
  observation_shape: [26]
  action_shape: []

model:
  actor: "Transformer"
  actor_params:
    state_dim: 26
    act_dim: 1
    K: 25
    max_ep_len: 48
    hidden_size: 64
    d_model: 64
    transformer_num_layers: 3
    nhead: 1
    dim_feedforward: 256
    activation: "relu"
    dropout: 0.1
  strategy: "AlphaPartialPunisherStrategy"

train:
  batch_size: 128
  num_epochs: 250
  steps_per_epoch: 100
  actor_optimizer: "AdamW"
  actor_optimizer_params:
    lr: 1e-4
  trajectory_window: 25

logging:
  log_dir: "logs/dt"
  checkpoint_interval: 1000
  use_wandb: true
